(define-module (home ssh)
  #:use-module (gnu home services ssh)
  #:use-module (gnu services)
  #:use-module (guix gexp)
  #:export (home-ssh-config))

(define home-ssh-hosts
  (list (openssh-host (name "github.com")
                      (user "git")
                      (identity-file "~/.ssh/github"))
        (openssh-host (name "codeberg.org")
                      (user "git")
                      (identity-file "~/.ssh/github"))
        (openssh-host (name "lexihk")
                      (host-name "lexihk.dimsumlabs.com")
                      (user "azz")
                      (port 2200))
        (openssh-host (name "lexijarod")
                      (host-name "91.181.156.239")
                      (user "root")
                      (port 7210)
                      (identity-file "~/.ssh/lexidoo"))
        (openssh-host (name "lexipine")
                      (host-name "192.168.0.13")
                      (user "azz")
                      (port 2200)
                      (identity-file "~/.ssh/lexipine"))
        (openssh-host (name "lexipve")
                      (host-name "192.168.0.206")
                      (user "root")
                      (port 22)
                      (identity-file "~/.ssh/lexipve"))
        (openssh-host (name "pveweb")
                      (host-name "192.168.0.76")
                      (user "sibl")
                      (port 22)
                      (identity-file "~/.ssh/pveweb"))
        (openssh-host (name "lexisense")
                      (host-name "10.38.0.1")
                      (user "admin")
                      (port 22)
                      (identity-file "~/.ssh/pfsense_odoo"))
        (openssh-host (name "rincewind")
                      (host-name "rincewind.trouble.is")
                      (user "azz")
                      (port 22)
                      (identity-file "~/.ssh/rincewind"))
        (openssh-host (name "labodoo")
                      (host-name "10.31.0.50")
                      (user "odoo")
                      (port 22)
                      (identity-file "~/.ssh/labodoo"))
        (openssh-host (name "lexidoo")
                      (host-name "10.38.0.5")
                      (user "sibl")
                      (port 2200)
                      (identity-file "~/.ssh/lexidoo"))))

(define home-ssh-authorized-keys
  (list
   (plain-file "lexipine.pub" "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuFK16nVWpdxlZlGWoHwCMDLUtbP9uvJwpi7/Comx9j sibl@sibl")
   (plain-file "gpg_ssh.pub" "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLhOSwuzj0J74VPkb90Suky1roeMcj7Dt3J6Q9sU22GrWXPDCSIqKSzoXrYcNenRTKvJgw0qRIgTMWUUOCtBoXf8Q1AmbE/fzMa2EDQLtmylaOcOk7a6BhJmN2QjfwkDxb2t6BZSM7G1eOl2iOtWWY3F5QxbGU4locZYjeF16xOG+FOyDuvJldsJsAx/5lUcQvZfuwVACIpqxkto8Qab7qWLb4Qzj81fYtoGrTfdl5FuwAkVFsMlDLHSQzPmOrSMc4lRdcqyn5AqMl/hpzTKXP+1pqHOab5tykAO28//hG7I0n7JBC9J53CPrHFyUYLJznJQ4zIj3QjH4LvrCLVgaKI6rziuhurFFPDG47hchIXXysb4XWElMVD+nVu9y92nM9s6/Np47nsS1yn3jVmE2WLinGMk9z7sme4C05lepVW5sW77dG+hlv0OC4p0MPH1WN27LVwnYLWXQp0kElURMpBi4516RYNrQJ3hrdDlBXJj+pfocbTj5HvMqQph3S3OIazAqZ03dzlpzSwjVEU0eASjz6s/V0IvzMUEsJ+yHyCpimxUm1zRQ1hh6REnTCDLK4YPug/M9LHxK3aOzTFDNwZA1ot+NHjfiDmA26Myhrl74GjjRqT0AxLJ22kozVILtuf/0Ez6PpozzA4JLES7GZ9BngLPqWeAxrvuMLMJC5rw== openpgp:0x99DB3DBD")))

(define home-ssh-config
  (service home-openssh-service-type
           (home-openssh-configuration
            (hosts home-ssh-hosts)
            (authorized-keys home-ssh-authorized-keys))))

